# 服务端口
server:
    port: 8273
spring:
    application:
        name: service-oss
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
    # 环境设置：dev、test、prod
    profiles:
        active: dev
    #swagger3整合
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER

qiniu:
    accessKey: ${QINIU_ACCESS_KEY}
    secretKey: ${QINIU_SECRET_KEY}
    bucketName: siyu-bucket2
    url: sevzfr6k7.hn-bkt.clouddn.com

